### ISSUE TITLE
Issue when trying to run the scanner

### ISSUE THREAD

**Issue by panda2k** [Gehhilfe/vtc-scanner#1]
When running the scanner is starts okay when running `node server.js` but when going to the web interface it shows this error. `{"code":"ResourceNotFound","message":"/; caused by Error: ENOENT: no such file or directory, stat 'webapp/dist/'"}`

Any ideas who could be wrong? Could you please also create a readme sometime? It could help with people like me coming into your project. 

Thanks

**Comment by suriyaa** [comment]
@panda2k You should go to `http://127.0.0.1:4200/nodes`.
